### ISSUE TITLE
Create budicon for Google G

### ISSUE THREAD

**Issue by ntotten** [auth0/styleguide#185]
![image](https://user-images.githubusercontent.com/282782/27341941-ba56a234-55ac-11e7-96df-6a709e2387ed.png)

**Comment by vctrfrnndz** [comment]
Not sure we can add that to budicons as that is 3rd party icon set we bought. Anyway, budicon is a commodity, and I always strongly suggest using an svg, more importantly if its a 3rd party logo, otherwise we'd have to update/maintain them all the time. 

https://commons.wikimedia.org/wiki/File:Google_2015_logo.svg

https://commons.wikimedia.org/wiki/File:Google_%22G%22_Logo.svg
